name: Multiple java versions
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17,21]
    steps:
      - uses: actions/checkout@v4
      - run: echo "Testing with Java ${{ matrix.java }} "
